### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by jposterloh** [tmyroadctfig/swingx#3]
Hi, 

as java.net and kenai is now dead, too, there is no website for this very useful library. Any plans on setting up the website anywhere, e.g. github, so that all links etc are working again? 

Best regards
Jan-Patrick

**Comment by tmyroadctfig** [comment]
Hi Jan-Patrick,

Unfortunately I don't have any plans to set up a website. This is just my personal fork of the library with some fixes from a guy at my work. Unfortunately I don't have any time to work on it further.

Cheers, Luke

**Comment by jposterloh** [comment]
Ok, to bad...
