### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by vincenzopalazzo** [tmyroadctfig/swingx#4]
Hello 
I'm a junior java developer and I'm a fan for swing and I'm a contributor for [material-ui-swing](https://github.com/atarw/material-ui-swing).
I think for creating a new component for java swing with the java swingx project and example
- [Toast component](https://github.com/vincenzopalazzo/toasts-for-swing)
- [Material Color Chooser style](https://github.com/vincenzopalazzo/material-ui-swing/issues/42)
- [Material Task Pane style](https://github.com/vincenzopalazzo/material-ui-swing/issues/30)

But i'm a student and not have more time for work in the project only, if you want We can join forces to create a 2.0 version that makes swing a more current framework.

Let me know.
Vincent

**Comment by tmyroadctfig** [comment]
Hi Vincent,

This is just a fork of the original swingx code with a few bug fixes my company needed. I'm not actively working on it, and probably will not touch it again.

All the best with your work on material-ui-swing though. That looks like a really neat project!

Cheers, Luke

**Comment by vincenzopalazzo** [comment]
Thanks for you good world

> All the best with your work on material-ui-swing though. That looks like a really neat project!

And thanks for your answer
